function StoryCard(props){
    const id = props.id
    return <div id={id} class={"StoryCard"}>
        <center>
            <h1>{id}</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vitae arcu in massa fringilla euismod vitae et ipsum. Quisque at magna in leo tincidunt gravida ut sit amet lectus. Proin feugiat mauris vitae aliquet efficitur. Cras malesuada ligula non ligula scelerisque euismod. Sed sit amet ligula vel tellus gravida bibendum. Maecenas eu consectetur purus. Aenean laoreet lacinia diam, bibendum mattis est. Donec tellus neque, maximus at mauris et, egestas tincidunt nisl. In elit mauris, tristique pharetra magna at, pharetra maximus magna. Proin semper pellentesque nisi ac tempus. Phasellus vel tortor tristique, facilisis enim ut, gravida enim. Cras at tempor nisi, quis sollicitudin mauris. Nulla varius scelerisque lectus, ac ullamcorper dolor volutpat eu</p>
            <p>Nullam imperdiet ligula at consectetur facilisis. Nam convallis tellus mauris, at pharetra augue congue sed. Donec eros quam, sodales ut nisi ac, placerat aliquam lacus. Vestibulum odio ligula, aliquet sit amet sapien eget, blandit molestie nunc. Morbi suscipit, quam et laoreet commodo, enim justo rhoncus nunc, sed rutrum nulla turpis eu nibh. Ut eget mauris nec nisl porta eleifend. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent rutrum erat ex, et posuere neque efficitur ac.</p>
            <p>Nulla porttitor libero in iaculis euismod. Sed eleifend urna in risus tincidunt, eu mollis justo vulputate. Sed nec nisl a ante fringilla pretium sed quis erat. Pellentesque at eros dignissim, ornare libero et, dapibus ante. Aliquam blandit, nibh ut maximus rhoncus, urna diam dapibus nibh, non viverra velit risus quis velit. Donec at gravida felis, ac lacinia lorem. Quisque eu ipsum non nisi molestie volutpat aliquam vitae nisi. In faucibus ut dolor vitae accumsan. Suspendisse vitae finibus neque, non consectetur ex. Suspendisse odio urna, venenatis a euismod ut, aliquam a metus.</p>
            <p>Curabitur rhoncus turpis fringilla elit porta, sit amet aliquam quam suscipit. Donec quis purus neque. Maecenas ornare est lorem. Sed pulvinar elementum iaculis. Aenean lobortis blandit varius. Quisque gravida accumsan neque, at commodo augue aliquam sit amet. Duis non ipsum in ex viverra fermentum. Fusce sollicitudin lorem ac malesuada porta. Aliquam malesuada blandit neque.</p>
            <p>Aenean lectus dui, accumsan id libero vel, ultrices ultricies neque. Donec fringilla ultrices elit eu varius. Maecenas id tortor vehicula, blandit quam vitae, feugiat neque. Donec mollis, augue ut porttitor pretium, mauris ante dapibus orci, non volutpat dui erat vitae purus. Nunc maximus luctus sollicitudin. Nullam non finibus felis. Quisque facilisis massa ex, vitae accumsan risus iaculis eu. Vivamus ornare elementum velit ut gravida. Integer eu pulvinar elit, at gravida ante. Quisque eget justo odio. Ut a efficitur est. Phasellus at fringilla ligula. Sed id est vitae enim pharetra semper. Nulla vel tortor eu libero maximus hendrerit et id lorem.</p>
            <p>Curabitur rhoncus turpis fringilla elit porta, sit amet aliquam quam suscipit. Donec quis purus neque. Maecenas ornare est lorem. Sed pulvinar elementum iaculis. Aenean lobortis blandit varius. Quisque gravida accumsan neque, at commodo augue aliquam sit amet. Duis non ipsum in ex viverra fermentum. Fusce sollicitudin lorem ac malesuada porta. Aliquam malesuada blandit neque.</p>
            <p>Aenean lectus dui, accumsan id libero vel, ultrices ultricies neque. Donec fringilla ultrices elit eu varius. Maecenas id tortor vehicula, blandit quam vitae, feugiat neque. Donec mollis, augue ut porttitor pretium, mauris ante dapibus orci, non volutpat dui erat vitae purus. Nunc maximus luctus sollicitudin. Nullam non finibus felis. Quisque facilisis massa ex, vitae accumsan risus iaculis eu. Vivamus ornare elementum velit ut gravida. Integer eu pulvinar elit, at gravida ante. Quisque eget justo odio. Ut a efficitur est. Phasellus at fringilla ligula. Sed id est vitae enim pharetra semper. Nulla vel tortor eu libero maximus hendrerit et id lorem.</p>
            <p>Curabitur rhoncus turpis fringilla elit porta, sit amet aliquam quam suscipit. Donec quis purus neque. Maecenas ornare est lorem. Sed pulvinar elementum iaculis. Aenean lobortis blandit varius. Quisque gravida accumsan neque, at commodo augue aliquam sit amet. Duis non ipsum in ex viverra fermentum. Fusce sollicitudin lorem ac malesuada porta. Aliquam malesuada blandit neque.</p>
            <p>Aenean lectus dui, accumsan id libero vel, ultrices ultricies neque. Donec fringilla ultrices elit eu varius. Maecenas id tortor vehicula, blandit quam vitae, feugiat neque. Donec mollis, augue ut porttitor pretium, mauris ante dapibus orci, non volutpat dui erat vitae purus. Nunc maximus luctus sollicitudin. Nullam non finibus felis. Quisque facilisis massa ex, vitae accumsan risus iaculis eu. Vivamus ornare elementum velit ut gravida. Integer eu pulvinar elit, at gravida ante. Quisque eget justo odio. Ut a efficitur est. Phasellus at fringilla ligula. Sed id est vitae enim pharetra semper. Nulla vel tortor eu libero maximus hendrerit et id lorem.</p>
        </center>
        
    </div>
}


export default StoryCard;